INSERT INTO public.role(id, name, is_admin, is_accountant, is_normal, description)
    VALUES (1, 'Standard',TRUE , FALSE , FALSE, 'Standardowy pracownik');
INSERT INTO public.department(id, department_name, department_description)
    VALUES (1, 'Zakon Feniksa', 'Zakon do walki ze złem');

INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (1, 'Hoover Ch82010 Ground Command Super Heavy-duty Air Mover, 12 A, 30 Lbs, Black', 2258, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (2, 'Rockwell Shopseries Variable Speed Jigsaw', 3051, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (3, 'Bostitch 7 Amp 4.5" Angle Grinder, Bte820k', 2094, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (4, 'Bosch Power Tools 2 Amp 1/4 Sheet Palm Sander 7292-01', 2706, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (5, 'Great Neck Saw Ra38 3/8" Drive Forward And Reverse Ratchet', 3043, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (6, 'Home Series 3 Pc Master Kit', 2180, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (7, 'Stalwart 41-piece Professional Screwdriver Bit And Socket Set', 3169, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (8, 'Chicago Power Tools Power Drill Accessory Set, 75-piece', 3465, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (9, 'Ingersoll Rand Hammer Pin', 2532, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (10, 'Primefit Industrial-grade Retractable Air Hose Reel With 50 Rubber Air Hose', 2130, 1, 1);
INSERT INTO employee_position (id, position_name, min_salary, role_id, department_id) VALUES (11, 'Aaa 300psi Air Compressor', 2226, 1, 1);

INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (1, 'Cassius', 'Lancaster', 'Cas.LANCASTE2719@reallymymail.com', 8, 12238);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (2, 'Finnegan', 'Walker', 'Finne.WAL4587@reallymymail.com', 9, 11348);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (3, 'Jeremy', 'Edwards', 'Jerem.EDWAR2501@dispostable.com', 5, 12809);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (4, 'Abrielle', 'Pugh', 'Abriel.PUGH8526@mailinator.com', 10, 16497);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (5, 'George', 'Velasquez', 'Georg.VELASQUEZ7463@yopmail.com', 2, 5042);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (6, 'Juan', 'Cox', 'Jua.CO9397@reallymymail.com', 5, 6986);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (7, 'Lilian', 'Serrano', 'Lil.SER5031@monumentmail.com', 2, 18980);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (8, 'Julieta', 'Maldonado', 'Juli.MALDONA7373@dispostable.com', 4, 6274);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (9, 'Kian', 'Phillips', 'Kia.PHILL4027@yopmail.com', 4, 11885);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (10, 'Bobby', 'Osborn', 'Bobb.OSB3439@yopmail.com', 2, 11327);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (11, 'Molly', 'Mcintosh', 'Molly.MCIN5463@reallymymail.com', 4, 15685);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (12, 'Renee', 'Dotson', 'Renee.DOTSO8058@dispostable.com', 3, 16421);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (13, 'Alyson', 'Blake', 'Alys.BL7749@monumentmail.com', 5, 15301);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (14, 'Cayson', 'Gentry', 'Cay.GENTRY3474@mailinator.com', 6, 11870);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (15, 'Bria', 'Bullock', 'Bria.BULLOC4697@mailinator.com', 2, 18274);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (16, 'Scott', 'Sims', 'Sc.SIM1239@mailinator.com', 4, 11070);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (17, 'Kamari', 'Burns', 'Kam.BURNS1367@mailinator.com', 6, 15674);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (18, 'Lance', 'Bennett', 'Lan.BENNET9645@yopmail.com', 3, 12067);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (19, 'Solomon', 'Lindsay', 'Sol.LINDSA3488@reallymymail.com', 1, 4362);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (20, 'Judah', 'Carlson', 'Judah.CARLSON6957@mailinator.com', 2, 11201);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (21, 'Kristina', 'Franklin', 'Kristin.FRANKLI4314@mailinator.com', 3, 5261);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (22, 'Hadassah', 'Bennett', 'Hadas.BEN6573@mailinator.com', 4, 4203);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (23, 'Milania', 'Moses', 'Mil.MOSES4590@yopmail.com', 5, 15348);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (24, 'Pierce', 'Steele', 'Pierce.STEE8565@reallymymail.com', 4, 6434);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (25, 'Noelle', 'Harmon', 'Noel.HARMON4223@yopmail.com', 5, 8677);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (26, 'Jaylon', 'Bernard', 'Jaylon.BERN6243@monumentmail.com', 9, 18809);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (27, 'Xavier', 'Hickman', 'Xav.HIC8025@mailinator.com', 9, 5815);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (28, 'Sonny', 'Cameron', 'So.CAME3033@mailinator.com', 4, 7259);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (29, 'Omari', 'Witt', 'Oma.WIT5750@mailinator.com', 10, 5648);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (30, 'Damon', 'Sherman', 'Dam.SHERMA4942@yopmail.com', 8, 15418);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (31, 'Alina', 'Fox', 'Alin.FOX5133@reallymymail.com', 6, 18594);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (32, 'Miya', 'Ryan', 'Miy.RY7040@mailinator.com', 9, 12536);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (33, 'Henry', 'Sykes', 'He.SY9067@dispostable.com', 5, 19846);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (34, 'Beckham', 'Castaneda', 'Beckham.CASTANE3681@yopmail.com', 4, 7491);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (35, 'Isaac', 'Burks', 'Is.BURKS4989@reallymymail.com', 2, 19323);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (36, 'Helena', 'Whitehead', 'Hel.WHITE6993@dispostable.com', 8, 7040);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (37, 'Jamarion', 'Zimmerman', 'Jamarion.ZIMMERMAN7939@monumentmail.com', 5, 5623);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (38, 'Nathanael', 'Raymond', 'Nathanae.RAYMOND3548@reallymymail.com', 10, 18314);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (39, 'Perla', 'Johns', 'Per.JOHN3551@dispostable.com', 8, 8306);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (40, 'Emmalee', 'Berg', 'Emmal.BERG1157@mailinator.com', 5, 11906);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (41, 'Charity', 'Gilbert', 'Chari.GIL2733@mailinator.com', 4, 16451);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (42, 'Brooks', 'Mccormick', 'Brooks.MCCORM6045@mailinator.com', 3, 12672);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (43, 'Sidney', 'Bernard', 'Sidney.BER4893@dispostable.com', 8, 7488);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (44, 'Marlee', 'Dominguez', 'Mar.DOMIN7936@reallymymail.com', 4, 6757);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (45, 'Aniyah', 'Olsen', 'Ani.OL8912@monumentmail.com', 7, 6883);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (46, 'Ellis', 'Thornton', 'Ell.THOR4867@reallymymail.com', 9, 17138);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (47, 'Declan', 'Hewitt', 'Dec.HEW2052@dispostable.com', 2, 4354);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (48, 'Cash', 'Mitchell', 'Cash.MITCHELL3746@monumentmail.com', 5, 10337);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (49, 'Cayson', 'Jimenez', 'Cays.JIMEN3753@reallymymail.com', 6, 15843);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (50, 'Leon', 'Jefferson', 'Leon.JEFFERSO3646@yopmail.com', 7, 5759);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (51, 'Jamal', 'England', 'Ja.ENGLA6911@dispostable.com', 3, 18571);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (52, 'Jaylin', 'Velazquez', 'Jayli.VELAZQUEZ8020@reallymymail.com', 7, 18462);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (53, 'Daniella', 'Clark', 'Daniell.CL6899@yopmail.com', 1, 11072);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (54, 'Gilberto', 'Jarvis', 'Gilber.JARV4859@yopmail.com', 7, 11971);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (55, 'Iris', 'Ruiz', 'Iris.RU4649@reallymymail.com', 7, 13179);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (56, 'Gwyneth', 'Aguilar', 'Gwynet.AGUILAR7784@dispostable.com', 3, 14102);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (57, 'Mara', 'Sanford', 'Mara.SAN4016@mailinator.com', 6, 6518);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (58, 'Alison', 'Morales', 'Alison.MORALES7177@monumentmail.com', 4, 19555);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (59, 'Samantha', 'Dyer', 'Samant.DYE7453@mailinator.com', 7, 16143);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (60, 'Tess', 'Huffman', 'Te.HUFFMA9139@mailinator.com', 6, 12407);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (61, 'Kamryn', 'Charles', 'Kamryn.CHARL7598@monumentmail.com', 3, 12509);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (62, 'Maverick', 'Mcbride', 'Maveri.MCBRID5819@yopmail.com', 6, 5429);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (63, 'Mckinley', 'Colon', 'Mckinle.CO1140@mailinator.com', 3, 6093);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (64, 'Ezequiel', 'Daugherty', 'Ezeq.DAUGHE8902@dispostable.com', 3, 11484);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (65, 'Gracelynn', 'Singleton', 'Gracely.SING4663@monumentmail.com', 6, 6501);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (66, 'Maleah', 'Robinson', 'Male.ROBI2775@mailinator.com', 2, 15117);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (67, 'Darryl', 'Gallagher', 'Darryl.GALLA4324@reallymymail.com', 6, 16038);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (68, 'Amelia', 'Conway', 'Ameli.CONWA4549@dispostable.com', 7, 11742);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (69, 'Leonidas', 'Cleveland', 'Leoni.CLEVEL4337@reallymymail.com', 6, 4224);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (70, 'Kaylynn', 'Brennan', 'Kaylyn.BREN7841@yopmail.com', 6, 11678);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (71, 'Brycen', 'Daniels', 'Bryce.DANIELS7441@yopmail.com', 8, 16896);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (72, 'Crew', 'Rogers', 'Cre.ROGERS8839@yopmail.com', 3, 14619);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (73, 'Kyler', 'Brock', 'Kyle.BRO6252@monumentmail.com', 5, 11038);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (74, 'Yuliana', 'Reyes', 'Yuliana.RE9870@reallymymail.com', 8, 10929);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (75, 'Howard', 'Maldonado', 'How.MALDONAD1314@reallymymail.com', 5, 10628);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (76, 'Megan', 'Glenn', 'Meg.GLEN4927@reallymymail.com', 5, 11503);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (77, 'Justin', 'Foreman', 'Jus.FOREM9839@yopmail.com', 5, 5307);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (78, 'Ian', 'Moss', 'I.MOSS1468@mailinator.com', 2, 11762);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (79, 'Karter', 'Logan', 'Karter.LOGA2003@monumentmail.com', 1, 14805);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (80, 'Aspen', 'Hoover', 'Aspe.HOOVER2007@dispostable.com', 4, 9650);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (81, 'Chase', 'Cole', 'Chas.CO6220@yopmail.com', 1, 13605);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (82, 'Antoine', 'Lott', 'Ant.LOT2121@mailinator.com', 10, 18378);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (83, 'Dexter', 'Klein', 'Dexte.KLEIN8763@yopmail.com', 2, 8410);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (84, 'Sasha', 'Chavez', 'Sa.CHAVEZ8284@yopmail.com', 1, 17931);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (85, 'Lyric', 'Gutierrez', 'Lyr.GUTIER7480@mailinator.com', 2, 5571);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (86, 'Catherine', 'Murphy', 'Catherin.MURP8228@monumentmail.com', 7, 7239);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (87, 'Brenna', 'Lester', 'Bre.LESTE9528@reallymymail.com', 2, 8694);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (88, 'Erica', 'Morris', 'Erica.MORR6811@yopmail.com', 4, 15195);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (89, 'Carly', 'Wyatt', 'Carly.WYATT4555@dispostable.com', 7, 12222);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (90, 'Javier', 'Benson', 'Javier.BENSO3064@dispostable.com', 2, 15557);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (91, 'Yosef', 'Gordon', 'Yo.GOR1104@monumentmail.com', 10, 4897);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (92, 'Ty', 'Doyle', 'Ty.DOYLE4424@mailinator.com', 1, 8090);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (93, 'Leilani', 'Barron', 'Leil.BARRO2255@dispostable.com', 5, 11531);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (94, 'Marlene', 'Haynes', 'Marl.HAY2116@mailinator.com', 6, 4136);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (95, 'Annika', 'Ramos', 'Ann.RAMOS9184@dispostable.com', 9, 6645);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (96, 'Briella', 'Pruitt', 'Briella.PRUIT1369@reallymymail.com', 4, 17125);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (97, 'Harold', 'Adams', 'Har.AD9906@yopmail.com', 2, 9092);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (98, 'Carlos', 'Curry', 'Carlos.CURR5804@dispostable.com', 9, 15369);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (99, 'Jessie', 'Stephenson', 'Jessi.STEPHENSO4423@dispostable.com', 8, 4834);
INSERT INTO employee (id, name, surname, email, position_id, salary) VALUES (100, 'Paxton', 'Mcpherson', 'Paxton.MCPHERS6522@mailinator.com', 8, 9808);
